SATapp.UI.MVC/Controllers/StudentStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SATapp.DATA.EF.Models;

namespace SATapp.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StudentStatusController : Controller
    {
        private readonly SATContext _context;

        public StudentStatusController(SATContext context)
        {
            _context = context;
        }

        // GET: StudentStatus
        public async Task<IActionResult> Index()
        {
              return _context.StudentStatuses != null ? 
                          View(await _context.StudentStatuses.ToListAsync()) :
                          Problem("Entity set 'SATContext.StudentStatuses'  is null.");
        }

        

        public async Task<IActionResult> TiledStudents()
        {
            var students =  _context.StudentStatuses;
                
            return View(await students.ToListAsync());
        }

        // GET: StudentStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StudentStatuses == null)
            {
                return NotFound();
            }

            var studentStatus = await _context.StudentStatuses
                .FirstOrDefaultAsync(m => m.Ssid == id);
            if (studentStatus == null)
            {
                return NotFound();
            }

            return View(studentStatus);
        }

        // GET: StudentStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Ssid,Ssname,Ssdescription")] StudentStatus studentStatus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(studentStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(studentStatus);
        }

        // GET: StudentStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StudentStatuses == null)
            {
                return NotFound();
            }

            var studentStatus = await _context.StudentStatuses.FindAsync(id);
            if (studentStatus == null)
            {
                return NotFound();
            }
            return View(studentStatus);
        }

        // POST: StudentStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Ssid,Ssname,Ssdescription")] StudentStatus studentStatus)
        {
            if (id != studentStatus.Ssid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studentStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentStatusExists(studentStatus.Ssid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(studentStatus);
        }

        // GET: StudentStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StudentStatuses == null)
            {
                return NotFound();
            }

            var studentStatus = await _context.StudentStatuses
                .FirstOrDefaultAsync(m => m.Ssid == id);
            if (studentStatus == null)
            {
                return NotFound();
            }

            return View(studentStatus);
        }

        // POST: StudentStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StudentStatuses == null)
            {
                return Problem("Entity set 'SATContext.StudentStatuses'  is null.");
            }
            var studentStatus = await _context.StudentStatuses.FindAsync(id);
            if (studentStatus != null)
            {
                _context.StudentStatuses.Remove(studentStatus);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentStatusExists(int id)
        {
          return (_context.StudentStatuses?.Any(e => e.Ssid == id)).GetValueOrDefault();
        }
    }
}

SATapp.UI.MVC/Views/StudentStatus/Create.cshtml
@model SATapp.DATA.EF.Models.StudentStatus

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StudentStatus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ssname" class="control-label"></label>
                <input asp-for="Ssname" class="form-control" />
                <span asp-validation-for="Ssname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ssdescription" class="control-label"></label>
                <input asp-for="Ssdescription" class="form-control" />
                <span asp-validation-for="Ssdescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SATapp.UI.MVC/Views/StudentStatus/Delete.cshtml
@model SATapp.DATA.EF.Models.StudentStatus

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentStatus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ssname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ssname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ssdescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ssdescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Ssid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SATapp.UI.MVC/Views/StudentStatus/Details.cshtml
@model SATapp.DATA.EF.Models.StudentStatus

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StudentStatus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ssname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ssname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ssdescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ssdescription)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Ssid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SATapp.UI.MVC/Views/StudentStatus/Edit.cshtml
@model SATapp.DATA.EF.Models.StudentStatus

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StudentStatus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Ssid" />
            <div class="form-group">
                <label asp-for="Ssname" class="control-label"></label>
                <input asp-for="Ssname" class="form-control" />
                <span asp-validation-for="Ssname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ssdescription" class="control-label"></label>
                <input asp-for="Ssdescription" class="form-control" />
                <span asp-validation-for="Ssdescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SATapp.UI.MVC/Views/StudentStatus/Index.cshtml
@model IEnumerable<SATapp.DATA.EF.Models.StudentStatus>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-action="TiledStudents">Tile View</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ssname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ssdescription)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ssname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ssdescription)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Ssid">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Ssid">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Ssid">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SATapp.UI.MVC/Views/StudentStatus/TiledStudents.cshtml
@model IEnumerable<SATapp.DATA.EF.Models.StudentStatus>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-action="Index">Table View</a>
</p>
<div class="row">

    @foreach (var students in Model)
    {
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="box">
                <div class="option_container">
                    <div class="options">
                        <a asp-action="Details"
                           asp-route-id="@students.Ssname"
                           class="option1">
                            @students.Ssname
                        </a>
                        <a asp-action="Delete"
                           asp-controller="StudentStatus"                           
                           class="option2">
                            Delete
                        </a>
                    </div>
                </div>
                <div class="img-box">
                    <img src="~/">
                </div>
                
            </div>
        </div>

    }


</div>